export const gifts = {
  _3_4: [
    "Saliva is a powerful acid",
    "Invisible while squeezing eyes shut",
    "Can manipulate wood with hands like clay",
    "Can dislodge own soul to look into the spirit world by taking 1 Fatigue",
    "Can secretly steal small objects with a mere touch",
    "Flammable touch & heat-resistant",
  ],
  _5: [
    "30ft prehensile tongue",
    "Perfect throwing accuracy, except when targeting a living creature",
    "When squeezing one eye shut, can see in the dark, but not in the light",
    "Briefly very strong after taking strong alcohol",
    "Can conjure an extra arm",
    "Climb any surface while hands & feet are bare",
  ],
  _6: [
    "Body parts can be detached and reattached, can control detached parts at range",
    "While pointing, the target is completely silent",
    "Can hock up a very sticky ball of gunk",
    "Gale-force sneeze",
    "Can leap a long distance, fall from any height unharmed",
    "Voice can come from somewhere nearby",
  ],
  _7: [
    "Can change someone's face at a touch. Reverts when washed",
    "Can extrude & retract long, indestructible hair",
    "Bloodhound-scent while eyes are closed",
    "Freezing touch & cold-resistant",
    "Perfect balance",
    "Can dig a hole or tunnel very fast",
  ],
  _8: [
    "Can transform into a horse",
    "Can summon one starting item at will",
    "Shrink self & gear to 10% of original size",
    "Excellent swimming & don't need to breathe",
    "Echolocate by singing",
    "Can lay tasty green eggs",
  ],
  _9_10: [
    "Can bite through any material, and safely eat anything",
    "Communicate with any creature",
    "Can change own scent to anything",
    "Perfectly mimic someone's voice or replicate any sound heard before",
    "Slippery skin while holding breath",
    "Thrown coins & dice always land on the desired side",
  ],
}