export const items = {
  armor: [
    "None",
    "None",
    "None",
    "Brigandine (1 Armor)",
    "Brigandine (1 Armor)",
    "Brigandine (1 Armor)",
    "Brigandine (1 Armor)",
    "Brigandine (1 Armor)",
    "Brigandine (1 Armor)",
    "Brigandine (1 Armor)",
    "Brigandine (1 Armor)",
    "Brigandine (1 Armor)",
    "Brigandine (1 Armor)",
    "Brigandine (1 Armor)",
    "Chainmail (2 Armor)",
    "Chainmail (2 Armor)",
    "Chainmail (2 Armor)",
    "Chainmail (2 Armor)",
    "Chainmail (2 Armor)",
    "Plate (3 Armor)",
  ],
  helmets_shields: [
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "Helmet (1 Armor)",
    "Helmet (1 Armor)",
    "Helmet (1 Armor)",
    "Shield (1 Armor)",
    "Shield (1 Armor)",
    "Shield (1 Armor)",
    "Helmet & Shield (1 Armor each)",
  ],
  weapons: [
    "d6 melee, e.g. Dagger, Cudgel, Staff",
    "d6 melee, e.g. Dagger, Cudgel, Staff",
    "d6 melee, e.g. Dagger, Cudgel, Staff",
    "d6 melee, e.g. Dagger, Cudgel, Staff",
    "d4 ranged, e.g. Sling, Darts, Throwing Knives",
    "d4 ranged, e.g. Sling, Darts, Throwing Knives",
    "d6 bulky ranged, e.g. Longbow, Crossbow",
    "d6 bulky ranged, e.g. Longbow, Crossbow",
    "d8 melee, e.g. Sword, Mace, Axe",
    "d8 melee, e.g. Sword, Mace, Axe",
    "d8 melee, e.g. Sword, Mace, Axe",
    "d8 melee, e.g. Sword, Mace, Axe",
    "d8 melee, e.g. Sword, Mace, Axe",
    "d8 melee, e.g. Sword, Mace, Axe",
    "d6 ranged, e.g. Pistol, Revolver",
    "d6 ranged, e.g. Pistol, Revolver",
    "d10 bulky melee, e.g. Halberd, Warhammer, Battleaxe",
    "d10 bulky melee, e.g. Halberd, Warhammer, Battleaxe",
    "d10 bulky melee, e.g. Halberd, Warhammer, Battleaxe",
    "d8 bulky ranged, e.g. Rifle, Musket",
  ],
  gear: [
    "Air Bladder",
    "Antitoxin",
    "Cart (+4 slots, bulky)",
    "Chain (10ft)",
    "Fire Oil",
    "Gold Wire",
    "Grappling Hook",
    "Large Sack",
    "Large Trap",
    "Lockpicks",
    "Manacles",
    "Pick",
    "Pole (10ft)",
    "Spyglass",
    "Pulley",
    "Repellent",
    "Rope (25ft)",
    "Silver Dust",
    "Tinderbox",
    "Wolfsbane",
  ],
  tools: [
    "Bellows",
    "Bucket",
    "Caltrops",
    "Chalk (light)",
    "Chisel",
    "Cook Pots",
    "Crowbar",
    "Drill (Manual)",
    "Fishing Rod",
    "Glue",
    "Grease",
    "Hammer",
    "Hourglass",
    "Metal File",
    "Nails",
    "Net",
    "Saw",
    "Sealant",
    "Shovel",
    "Tongs",
  ],
  trinkets: [
    "Bottle",
    "Card Deck",
    "Dice Set",
    "Face Paint",
    "Fake Jewels",
    "Horn",
    "Incense",
    "Instrument",
    "Lens",
    "Marbles",
    "Mirror",
    "Perfume",
    "Quill & Ink",
    "Salt Pack",
    "Small Bell",
    "Soap",
    "Sponge",
    "Tar Pot",
    "Twine",
    "Whistle",
  ],
  bonus: [
    "Trinket",
    "Trinket",
    "Trinket",
    "Trinket",
    "Tool",
    "Tool",
    "Tool",
    "Tool",
    "Expeditionary Gear",
    "Expeditionary Gear",
    "Expeditionary Gear",
    "Expeditionary Gear",
    "Expeditionary Gear",
    "Expeditionary Gear",
    "Weapon",
    "Weapon",
    "Wand",
    "Wand",
    "Wand",
    "Wand",
  ],
}
