export const items = {
  gear: [
    "Air Bladder",
    "Antitoxin",
    "Cart (+4 slots, bulky)",
    "Chain (10ft)",
    "Fire Oil",
    "Gold Wire",
    "Grappling Hook",
    "Large Sack",
    "Large Trap",
    "Lockpicks",
    "Manacles",
    "Pick",
    "Pole (10ft)",
    "Spyglass",
    "Pulley",
    "Repellent",
    "Rope (25ft)",
    "Silver Dust",
    "Tinderbox",
    "Wolfsbane",
  ],
  tools: [
    "Bellows",
    "Bucket",
    "Caltrops",
    "Chalk (light)",
    "Chisel",
    "Cook Pots",
    "Crowbar",
    "Drill (Manual)",
    "Fishing Rod",
    "Glue",
    "Grease",
    "Hammer",
    "Hourglass",
    "Metal File",
    "Nails",
    "Net",
    "Saw",
    "Sealant",
    "Shovel",
    "Tongs",
  ],
  trinkets: [
    "Bottle",
    "Card Deck",
    "Dice Set",
    "Face Paint",
    "Fake Jewels",
    "Horn",
    "Incense",
    "Instrument",
    "Lens",
    "Marbles",
    "Mirror",
    "Perfume",
    "Quill & Ink",
    "Salt Pack",
    "Small Bell",
    "Soap",
    "Sponge",
    "Tar Pot",
    "Twine",
    "Whistle",
  ],
}
